# Generated by Django 5.2.7 on 2025-11-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
